### ISSUE TITLE
建议将README中的dev-master去掉

### ISSUE THREAD

**Issue by tinpont** [freyo/flysystem-qcloud-cos-v3#3]
目前你已经发布1.0版本了，可以将README中的dev-master去掉了。

PS：兄弟，找了一圈的COS第三方库（官方的我就不多说了），就你的符合人类使用习惯，感谢了，如果需要协助，随时@我。

**Comment by freyo** [comment]
哈哈，感谢支持，README中的dev-master已经去掉了。

**Comment by tinpont** [comment]
看了一下好像你还未发布到https://packagist.org ，你去这个网站注册一个账号，然后在这个项目添加一个webhook，这样子每一次发布都会自动通知packagist了，其他人就可以直接composer update你的发布版本。

**Comment by tinpont** [comment]
才注册的COS，只能用COSV4版本了，有点蛋疼，我Fork一下自己改改。
