### ISSUE TITLE
建议：修改一下项目名

### ISSUE THREAD

**Issue by tinpont** [freyo/flysystem-qcloud-cos-v3#5]
目前我是fork了一份自己改，因为我发现你的名字里面带有版本号，不好直接提交pull request。我建议通过branch的方式来区分v3还是v4版本，然后在README里面标明如果像用V3请require "~1.0"版本，这样子就可以并行开发。

名字要改的话，adapter最好不要用，感觉没啥意义。我见过众多Laravel Storage扩展库都是直接以flysystem开头的。

建议叫 flysystem-cos或者flysystem-qcloud-cos，这样子一来很清晰你这个项目是跟flysystem兼容的，二来这个东西不止用于laravel可以扩大影响度，laravel支持可以在README里面表明，这样也有利于别人搜索进来。

**Comment by freyo** [comment]
那个只是我pr的时候进错了项目:laughing:，抱歉了。
项目名称这个建议不错，我稍后更改。

**Comment by tinpont** [comment]
非常感谢抽空做了v4版本，感激不尽，有空我也会多多提交pull request完善这个项目的。
